### PR TITLE
Eclipse install instructions

### PR DESCRIPTION
**Pull request by politas**
Adds instructions for Eclipse IDE

### CODE REVIEW

**Comment by politas** [comment]
I'm not sure these instructions are complete/correct. Needs more investigation.

This is all I'm getting for Java completion hints:
typing hint fail
Whereas, for Python code in referenced projects or builtins, I get something more like your example:
typing hint success
typing hint success code

I'm trying to find better advice on .pyi files, but my Google-fu is failing me.

**Comment by CrazyIvan359** [comment]
Did you move 3 sets of stubs? You should have one for OH, one for Java, and the third from the HL repo itself. The only set I can be sure you have available is the HL ones. If you are working in the HL repo and have not copied in OH and Java stubs then this is what I would expect to see. The only stubs in the HL repo are the ones for the HLs themselves, you can copy the OH and Java stubs into the existing typings folder in the HL repo (git will ignore them) to get the full experience there.

**Comment by politas** [comment]
Ah, that could be it. I might have only done two, but I thought I followed all the instructions for copying the stub files. I'll check.

**Comment by CrazyIvan359** [comment]
Actually that makes sense, I was not able to pull any javadoc for the Java stuff, only openHAB. Do you see overloads when you finish typing `now`?

image

**Comment by politas** [comment]
Nope, I definitely included all the stubs: actions, core, java, javax, and org

I get those two `now(clock)` and `now(zoneId)` list entries as shown above, but no hints as to the type returned or the types for those parameters as shown in the screenshot you pasted [here](https://community.openhab.org/t/jython-helper-libraries-for-oh3/110734/50)

**Comment by politas** [comment]
Ok, there's a few options for docstrings that will provide type hinting in PyDev/Eclipse [here] (https://www.pydev.org/manual_adv_type_hints.html)

Can you point me to how you're generating these .pyi files? Maybe we can add the necessary docstrings for PyDev. I gather Eclipse is the preferred IDE for the Openhab project maintainers, so supporting it is probably worthwhile?

**Comment by CrazyIvan359** [comment]
I'm still working on getting the generation cleaned up and made into a mostly automated process. The original method was very ad-hoc.

I have not had time to really dig into it to see why were only getting some of the javadoc and how to pull the docs for the Java code itself (I have the HTML help in a zip). 

Eclipse is the preferred IDE for openHAB, which is written in Java. You are working on scripting (rules) using third party libraries, all external to the openHAB project. ie use whatever IDE you want. For me and a lot of others that's VSCode, so that's what I will support with my limited time, but I am happy to help you to get it working in Eclipse and get your guide merged for others to use.

**Comment by politas** [comment]
> You are working on scripting (rules) using third party libraries, all external to the openHAB project. ie use whatever IDE you want. For me and a lot of others that's VSCode, so that's what I will support with my limited time, but I am happy to help you to get it working in Eclipse and get your guide merged for others to use.

Lovely. Are you planing on using this repo for the automation code? I'm happy to add stuff for Eclipse if it doesn't break your use case.

**Comment by CrazyIvan359** [comment]
No, the stub generation code will go in another repo for licensing reasons. But the stubs are the same no matter what IDE you use.

**Pull request closed without merging**
